### PR TITLE
Add support for custom WP Roles

### PR DESCRIPTION
**Pull request by zSeriesGuy**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. (WPCS)
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by zSeriesGuy** [comment]
This change changes the capability_type of the Sermon custom post type from "posts" to "wpfc_sermon". This will allow anyone using a role manager to grant or deny access to the SM functions thus allowing delegation of contribution and management.

**Comment by nikola3244** [comment]
This is looking great, I'll just move the code for adding capabilities to default roles into a new file, since they are currently in the file specifically for post types, but that's nothing to worry about :slightly_smiling_face:

Great contribution, thanks again! It will be merged tomorrow

**Comment by zSeriesGuy** [comment]
I see you fixed some code formatting. Sorry about that. Using this github pencil editor makes it kind of hard to get things lined up correctly. I'll have to figure out how to go about downloading and editing using my desktop software and then re-uploading.

**Comment by nikola3244** [comment]
It's alright, don't worry about it - it happens to the best as well. Anyway, it's not bothering me, since my editor fixes those errors in one keystroke. Nothing to worry about :slightly_smiling_face:

**Pull request merged**
