### PR TITLE
Updates and fixes to translations

### PR DESCRIPTION
**Pull request by GITNE**

### CODE REVIEW

**Comment by nikola3244** [comment]
We are not doing something right regarding languages and GlotPress.

I went to take a look how [Akismet](https://wordpress.org/plugins/akismet/) does it, for example.
 * Minimum required WordPress version is 4.0 ([source](https://plugins.svn.wordpress.org/akismet/tags/4.0/readme.txt)) - so seems like modifying minimum WordPress version is not required.
 * They have *no* `.pot`, `.po` or `.mo` files.
 * They have a nice and working [GlotPress page](https://translate.wordpress.org/projects/wp-plugins/akismet).
 * They only call `load_plugin_textdomain( 'akismet' );`

So, based on those conclusions, I assume that we should:
 * import `.po/mo` files to GlotPress (for initial translation) and completely remove them from plugin
 * Modify https://github.com/WP-for-Church/Sermon-Manager/blob/dev/sermons.php#L206 to `load_plugin_textdomain( 'sermon-manager-for-wordpress' );`
 * Remove https://github.com/WP-for-Church/Sermon-Manager/blob/dev/sermons.php#L13, since Akismet doesn't have such tag

I have tested [importing on GlotPress](https://translate.wordpress.org/projects/wp-plugins/sermon-manager-for-wordpress/dev/pl/default) (at the bottom of the table) and it works, but GlotPress shows 448 strings, while your Polish file has 320. GlotPress showing more than it exists? Your file didn't translate everything?

Anyway, I can request your wp.org account to be added as a (Polish and German) language project manager so you can approve translations, if you like. :)

**Comment by GITNE** [comment]
Thank you for digging into this. I appreciate your engagement very much. I have been looking into WordPress documentation and searching external sites about this too.

> We are not doing something right regarding languages and GlotPress.
> 
> I went to take a look how Akismet <https://wordpress.org/plugins/akismet/> does it, for example.
> 
>   * Minimum required WordPress version is 4.0 (source
>     <https://plugins.svn.wordpress.org/akismet/tags/4.0/readme.txt>) - so seems like modifying minimum WordPress version is not required.
>   * They have /no/ `.pot`, `.po` or `.mo` files.
>   * They have a nice and working GlotPress page
>     <https://translate.wordpress.org/projects/wp-plugins/akismet>.
>   * They only call `load_plugin_textdomain( 'akismet' );`

Right, I have been looking to the [Polylang](https://wordpress.org/plugins/polylang) plugin for reference since one might consider it’s developers as experts in the field of l10n for WordPress. However, looking for reference on how to do something is good but not the proper way to do things. The documentation or specification should be the document to follow but this of course requires these to be complete and unambiguous first. Having said that, I have not learned much from looking into Polylang as a reference either. The documentation is not clear on what the exact requirements are for GlotPress to work in your plugin, especially the wording in the info box of the section “[Loading Text Domain](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain)” is ambiguous and unclear. It gives mere hints than actually clarifying anything.

> So, based on those conclusions, I assume that we should:
> 
>   * import `.po/mo` files to GlotPress (for initial translation) and completely
>     remove them from plugin
>   * Modify https://github.com/WP-for-Church/Sermon-Manager/blob/dev/sermons.php#L206 to `load_plugin_textdomain( 'sermon-manager-for-wordpress' );`
>   * Remove https://github.com/WP-for-Church/Sermon-Manager/blob/dev/sermons.php#L13, since Akismet doesn't have such tag

You have basically got it covered. However, I see two major problems with GlotPress:

1. No version control over message IDs (`msgid`) and strings (`msgstr`). Hence, you **do not** know who modified what, when, and most importantly why.

2. Pulling strings from glotpress.org may not always work in all network or proxy configurations since it may be blocked for various reasons. So, local binary `.mo` resource files are they only way to get around this. But, even if it is not blocked, pulling in content from other sites always creates privacy issues. GlotPress will have or has records of which IP pulls what strings and when, and potentially also for how long. One can easily reconstruct from this data which pages have been viewed. This becomes particularly problematic in the case of admin pages.

Personally, I regard these two arguments as killer arguments. [Transifex](https://www.transifex.com) is not much better in this regard either. And, there is actually a third problem with this approach for developers themselves. They have to juggle message IDs and strings across tools and sites than having everything in one *text* editor. Testing is much more complicated and time consuming than having everything locally in simple text files at your hand.

> I have tested importing on GlotPress
> <https://translate.wordpress.org/projects/wp-plugins/sermon-manager-for-wordpress/dev/pl/default>
> (at the bottom of the table) and it works, but GlotPress shows 448 strings,
> while your Polish file has 320. GlotPress showing more than it exists? Your file
> didn't translate everything?

I think they may need to be approved first before they sort of go *green*. German and French is missing all together.
 
> Anyway, I can request your wp.org account to be added as a (Polish and German)
> language project manager so you can approve translations, if you like. :)

Thank you but I do not have a WordPress account and I also actually do not want one. It is 2017 and website operators still did not figure out SSO via OAuth or OpenID. :disappointed:

I am going to revert the version number changes in the `readme.txt` file but leave other modifications.

**Comment by GITNE** [comment]
Oh, perhaps I should add that I hoped that GlotPress would integrated with version control nicely, be it SVN or git, and that it was pulling data from `.po` and `.mo` files automatically and transparently. Transifex does incorporate version control integration but it is not really well designed and it does not serve message strings in the cloud. Plus, no solution makes lives of developers easier either. In other words, no solution actually lives up to the needs.

**Comment by nikola3244** [comment]
Hey, thanks for the detailed replies and patience, we had some troublesome bugs so I could not take a look at this until now.

>No version control over message IDs (msgid) and strings (msgstr). Hence, you do not know who modified what, when, and most importantly why.

I have done a quick research just now and seems like you are right, which is a bummer.

>Pulling strings from glotpress.org may not always work in all network or proxy configurations since it may be blocked for various reasons. So, local binary `.mo` resource files are they only way to get around this. But, even if it is not blocked, pulling in content from other sites always creates privacy issues. GlotPress will have or has records of which IP pulls what strings and when, and potentially also for how long. One can easily reconstruct from this data which pages have been viewed. This becomes particularly problematic in the case of admin pages.

Don't assume, test. 😉
WordPress does not query their API for every single string, it downloads precompiled `.mo` files created by GlotPress on user request. How to test: 
1. Install and activate Akismet
2. Open Settings -> General
3. Change language to some other language, Polish is fine since Akismet is translated into it
4. Save settings (WordPress will change the language while Akismet will stay the same - English only)
5. Go to Dashboard -> Updates
6. WordPress will notify you that there is an update available for your locale - click on update
7. `.mo` files for WordPress, themes and plugins will be downloaded

You can monitor `/wp-content/languages` for changes. Plugin locale files will be saved into `/wp-content/languages/plugins/slug-locale.mo`, themes in `/wp-content/languages/themes/slug-locale.mo` and WordPress core files would be in `/wp-content/languages`.

WordPress gets the language data (for plugins) from `http://api.wordpress.org/translations/plugins/1.0`.
A POST request is made with following data:
```
'wp_version' => $wp_version,
'locale'     => get_locale(),
'version'    => $args['version'], // Version of plugin
'slug'       => $args['slug'], // Slug of the plugin
```

If your second point were true, I would certainly be with you and not use GlotPress or any service that does the similar functionality. But, since it's not, we only have this one: 
>No version control over message IDs (msgid) and strings (msgstr). Hence, you do not know who modified what, when, and most importantly why.

I think that it's not a big issue, yeah, it's definitely a con, but check out the pros:
- Languages are maintained in the same way as in any other popular and modern WordPress plugin
- "Average Joe" can easily translate the plugin
- Effective UI
- Simpler, no need for the couple following actions:
- No need to rebuild `.pot`, `.po` and `.mo` files
- No need to install any software on the computer
- No formatting errors if user edits the `.po` file directly and makes a simple mistake (such as omitting `"`) 
- Only correct translations will get approved (only approved editors can "approve" a translation, users can only suggest strings)
- Sermon Manager will have a nice notice on the plugin page with call for help regarding translations

I probably missed some, but I guess that these are enough reasons to use GlotPress. 😄

**Comment by GITNE** [comment]
> WordPress gets the language data (for plugins) from http://api.wordpress.org/translations/plugins/1.0.

Well, this sounds like good news. :+1: However, this still does not eliminate all security side effect implications to consider. But, I am aware that it is no different from pulling in any other content from third party sites, or content which is outside of your control. Nevertheless, this adds to the slue of ever increasing vectors for malicious code injection, especially in the case of WordPress where strings can end up *unsanitized* on the server but also in the final page (it’s a bit different with images and fonts). Hence, approval must live up to its name. :wink:

> * Languages are maintained in the same way as in any other popular and modern WordPress plugin

Just because others do something has never been a valid argument, and never will be.
What you might have meant was that the plugin’s page will finally have all the available languages featured and because of that the page will look *prettier*. It’s true but it is more an effect of wordpress.org’s infrastructure than the facts.

Btw, it is a design mistake of GlotPress that you have to sign up and log in just to post translation proposals. There is no need for signing up or logging in if messages must be approved anyway (which is reasonable and good).

> * Simpler, no need for the couple following actions:
>   * No need to rebuild `.pot`, `.po` and `.mo` files
>   * No need to install any software on the computer

Does GlotPress support message contexts (`msgctxt`)?
What about translator comments?

> * No formatting errors if user edits the `.po` file directly and makes a simple mistake (such as omitting `"`)

Well, `msgfmt` does perform a syntax check before it will *compile* any `.po` file.

Personally, in the grand scheme of things, as of now, I really do not see any true advantage in having translations hosted in the cloud (besides the fact that it may pose a lower barrier for contributions from any potential non-technical translators), especially when version control integration is missing.
Of course, as project owner you are free to do whatever you want to do.

**Comment by nikola3244** [comment]
>Nevertheless, this adds to the slue of ever increasing vectors for malicious code injection, especially in the case of WordPress where strings can end up unsanitized on the server but also in the final page [...]

True. But the translations are coming from official WordPress code, so if there's vulnerability - millions of sites are compromised. I'm pretty sure that WordPress team has security experts that already thought of sanitizing strings and other security measures. 😉 

>Just because others do something has never been a valid argument, and never will be.

Yes, I agree completely. I have worded it wrong.
English is not my first language, so I apologize.

>Does GlotPress support message contexts (msgctxt)?
What about translator comments?

I'm afraid that it does not support it. Here's a screenshot before and after translating a string:
<kbd>
Before adding a new string:

</kbd>

<kbd>
Modifying the newly-added string (note: I do not have permission to _Approve_ a translation so that button is missing):

</kbd>

</br>

>[...] besides the fact that it may pose a lower barrier for contributions from any potential non-technical translators

This is IMO the primary reason to use GlotPress. Sermon Manager is not too popular, there aren't many technically knowledgeable people - at least they are not showing up for now. I could count people who know how to help on one hand. 😄 
But I hope that plugin development activity will motivate more people to contribute.

>Of course, as project owner you are free to do whatever you want to do.

Yup, but I do want to hear opinion of more knowledgeable people, such as you. :)
It's not about _what I want to do_, it's more about _what's best to do_, and that requires input from multiple people.
If I wanted to work alone on it, I would have set the repository as private - but that's not my desire at all and it never was. :)

**Comment by nikola3244** [comment]
Oh, I forgot to ask, is this PR ready for merging? 👍

**Comment by GITNE** [comment]
> Oh, I forgot to ask, is this PR ready for merging?

Sure, any time you like. If it merges without conflicts it is usually ready to go.

And, I’ll keep my `i18n` branch going. :wink:

**Comment by GITNE** [comment]
> True. But the translations are coming from official WordPress code, so if there's vulnerability - millions of sites are compromised. I'm pretty sure that WordPress team has security experts that already thought of sanitizing strings and other security measures. :wink:

In fact, it is not the way you think it is. It is on every plugin developer to escape any string before rendering. There is nothing WordPress can do here. They just serve `.mo` files.

>> Does GlotPress support message contexts (msgctxt)?
>> What about translator comments?
> I'm afraid that it does not support it. Here's a screenshot before and after translating a string:

Thank you for the screen shot. In trail of this it would also be interesting to know if GlotPress supports locale variants. This might become useful for locales like `sr_RS` where AFAIK both latin and cyrillic variants are used.

**Comment by nikola3244** [comment]
>In fact, it is not the way you think it is. It is on every plugin developer to escape any string before rendering. There is nothing WordPress can do here. They just serve .mo files.

Hehe, I actually think that it's not exactly the way you think it is. 😉 
Yeah, it's on on the plugin developer to escape strings, but I am also pretty sure that GlotPress is doing _some_ escaping and sanitizing themselves. I will have to test, but it would be insane that their web interface backend processing function is accepting non-escaped and non-sanitized text - that could hypothetically put GlotPress website under risk. Also, `.mo` files have to be generated from somewhere, so, logically, some escaping is necessary, right?

>In trail of this it would also be interesting to know if GlotPress supports locale variants. 

TL;DR: It does. 
Reading material: https://glotpress.blog/2017/07/12/glotpress-and-locale-variants/
Original issue: https://github.com/GlotPress/GlotPress-WP/issues/226

>This might become useful for locales like `sr_RS` where AFAIK both latin and cyrillic variants are used.

Yup, we use both variants. But when Cyrillic variant is translated, it's super easy to convert to Latin. Each Cyrillic character has its own Latin representation so it all comes to quick and simple search and replace in the end.

**Pull request merged**
